;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        bookmark-jump
        cycle-spacing
        fdx/insert-and-populate-org-shots
        fdx/reindent-buffer
        org-beginning-of-line
        org-end-of-line
        org-force-self-insert
        org-kill-line
        org-self-insert-command
        wdired--self-insert
        wdired-finish-edit
        yas-expand
        ))

(setq mc/cmds-to-run-once
      '(
        rspec-rerun
        ))
